### ISSUE TITLE
Design the Education Centre Badge and order with Fitwell ltd

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/TextAdventureTime#16]
Call Fitwell once designed they are "not a faceless dot com" and are on Smithdown Road in Liverpool so I can pick up the finished badge

http://www.fitwellpatches.co.uk/pages/Contact-Us.html

**Comment by hwayounggit** [comment]
[All badges.pdf](https://github.com/cheapjack/TextAdventureTime/files/81314/All.badges.pdf)

**Comment by hwayounggit** [comment]
Hi, Have created a PDF with all 4 badges (alpha, beta, omega, No VAT), the school emblem to be embroidered and FutureGen logo. Have two versions of the logo. Not sure which to use. Thoughts?

**Comment by hwayounggit** [comment]
The badges are 25mm, the school emblem I gave three colours but can be knocked down if it's too expensive. They are all vector so can scale. Have outlined font for FutureGen.

**Comment by cheapjack** [comment]
Will get this all over to fitwell and look up badge making. Sorry did not these were good to go! Fingers crossed can get them done for next week, imagine will be ok.
