### ISSUE TITLE
Confirm the plinth height

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/TextAdventureTime#23]
NB Plinth is now made of the Bosche extruded aluminium

**Comment by muff7** [comment]
That’s Bosch Rexroth Assembly
http://www.boschrexroth.com/en/xc/products/product-groups/assembly-technology/index

~ ~ ~ ~
Mark Murphy
markmurphy.co.uk

On 5 January 2016 at 19:20:55, Ross Dalziel @cheapjack (notifications@github.com) wrote:

NB Plinth is now made of the Bosche extruded aluminium

**Comment by cheapjack** [comment]
thanks @muff7 happy new year!

**Comment by cheapjack** [comment]
I **think** we said 900mm was a good height for the plinth @muff7 ?
