### ISSUE TITLE
Sign off and complete the plinth artwork

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/TextAdventureTime#26]
- [x] Remove the hyphens @cheapjack
- [x] Split the artwork into 7 sub-panels
  - [x] Use the green vitrine edges as the sub-panel artwork edges but with a 2.5mm bleed to allow for trimming artwork to fit acrylic vitrine
  - [x] Note the 7th sub-panel is the base layer with the NorthernPowerhouse text and timeline
- [x] Check Measurements of key objects @cheapjack
- [x] Complete the Timeline @hwayounggit #24
- [x] Change type to 14pt @hwayounggit 
- [x] Add plinth measurements layer to /MakeFiles/TextAdventureArtEFakeLayoutRevised.ai @cheapjack
- [x] @cheapjack Contact C3 & @muff7
  - [x] Find out file format/colour profile CMYK
  - [x] Find out turnaround
  - [x] Note the Dark edges for C3 for the print

**Comment by cheapjack** [comment]
@hwayounggit I've spoke with <a href="mailto:tomas.emmett@c3london.co.uk?subject=Northern PowerHouse Artwork">Tomas Emmett</a> at the London office of [C3](http://c3imaging.com/c3imaging-liverpool/) and he's suggested we'd print to 3mm Foamex with a dark-grey edge which costs slightly more than the white standard. He's ready to receive the 7 panels of artwork (follow the `mailto:` link to contact him) and knows the rough sizes and would require artwork in either hi-res `.pdf` or `.ai`

**Comment by cheapjack** [comment]
He would forward the artwork to liverpool office but we'd need to cc in @muff7 and provide FACT invoice details.

**Comment by hwayounggit** [comment]
Okay, I've pulled your .ai file down and am adjusting stuff on it. I don't think it's be ready till tomorrow though. I'll send you other logos you need first today.

**Comment by cheapjack** [comment]
Ok was about to push a new version with updated measurements should I wait and pull your file tomorrow then merge?

**Comment by cheapjack** [comment]
If you do the logos first then just put that in your updated file then send me it, I will add the measurements and push it to `master`. Or push it yourself.

**Comment by hwayounggit** [comment]
No, do it now and then I'll pull. I've only opened it to see the measurements I needed for the brainchip photo

**Comment by hwayounggit** [comment]
![brainchip-for-display](https://cloud.githubusercontent.com/assets/5999734/12172477/09d9b00e-b549-11e5-825e-5dd3f5ca9050.jpg)

**Comment by cheapjack** [comment]
ok will do

**Comment by cheapjack** [comment]
Just pushed the latest with measurements and removed the raised sub-plinth for the sacred book because we not doing that now

**Comment by cheapjack** [comment]
Will leave that file for today and let you take over and then seperate into different artboard/panels dont forger about the bleed for vitrine trimming

**Comment by hwayounggit** [comment]
Ok, thanks! So the panel sizes should be the same as the vitrine - so it can be trimmed later.

**Comment by hwayounggit** [comment]
[1 Comms.pdf](https://github.com/cheapjack/TextAdventureTime/files/85809/1.Comms.pdf)
[2 Cyborgs.pdf](https://github.com/cheapjack/TextAdventureTime/files/85810/2.Cyborgs.pdf)
[3 Emoji.pdf](https://github.com/cheapjack/TextAdventureTime/files/85811/3.Emoji.pdf)
[4 Book.pdf](https://github.com/cheapjack/TextAdventureTime/files/85812/4.Book.pdf)
[5 Ident.pdf](https://github.com/cheapjack/TextAdventureTime/files/85813/5.Ident.pdf)
[6 FutureGen.pdf](https://github.com/cheapjack/TextAdventureTime/files/85814/6.FutureGen.pdf)
[Main.pdf](https://github.com/cheapjack/TextAdventureTime/files/85815/Main.pdf)

**Comment by hwayounggit** [comment]
I've added 7 panels. Please take a look.

**Comment by cheapjack** [comment]
got it looking good will have a look thru and a proof and get back to you...

**Comment by hwayounggit** [comment]
Great! Worried about typos and consistency.

**Comment by cheapjack** [comment]
Looks great! Like the fonts! But just things to amend/check and tick off; margins consistency seems fine if thats what you mean

#### Amends / Typos

Some of the `.pdf` seem to have a mix of CMYK and RGB elements (could be my CS4's interpretations but worth checking but dont know enough about print to know if its a potential issue)
- [x] Checked

`Main.pdf`
- [x] The main artboard is only 1400 x 900 it needs to be 1470 x 900

`3.Emoji.pdf`
- [x] "...Traces of human ageing toxins found on **tis** item known..." t**h**is
- [x] "...DeathTurf© **see** to confirm the material could cause premature ageing. see**m**

**Comment by hwayounggit** [comment]
[3 Emoji.pdf](https://github.com/cheapjack/TextAdventureTime/files/85887/3.Emoji.pdf)
[Main.pdf](https://github.com/cheapjack/TextAdventureTime/files/85888/Main.pdf)

**Comment by hwayounggit** [comment]
Don't have to worry about CMYK/RGB now that it's going to digital print. Use to get anxious about it, but doesn't seem to be a problem now with .pdfs to send to printers. 

Have uploaded new Main.pdf and 3 Emoji.pdf

Thanks Ross. Can you send them off to print? Debbie is in tomorrow, but I think she's picking up emails today, and will for something time critical.

**Comment by cheapjack** [comment]
3 Emoji.pdf
Main.pdf
- [x] Checked
  Will send the `pdf`s to C3 in the morning
